variables:
    HTML_REPORT_SUBJECT:
      required: false
      type: string
      default:
      description: "Enter a custom report subject name."
    AUDIT_AWS_CLOUDWATCHLOGS_ALERT_LIST:
        required: false
        type: array
        default:
        description: "Which rules would you like to run? Possible values are cloudwatchlogs-inventory"
    AUDIT_AWS_CLOUDWATCHLOGS_ALLOW_EMPTY:
        description: "Would you like to receive empty reports? Options - true / false. Default is false."
        required: true
        type: boolean
        default: false
    AUDIT_AWS_CLOUDWATCHLOGS_SEND_ON:
        description: "Send reports always or only when there is a change? Options - always / change. Default is change."
        required: true
        type: string
        default: "change"
    AUDIT_AWS_CLOUDWATCHLOGS_ALERT_RECIPIENT:
        description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
        required: false
        type: string
        default:
    AUDIT_AWS_CLOUDWATCHLOGS_REGIONS:
        description: "List of AWS regions to check. Default is all regions. Choices are us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1,ap-south-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,eu-central-1,eu-west-1,eu-west-1,sa-east-1"
        required: true
        type: array
        default:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
            - ca-central-1
            - ap-south-1
            - ap-northeast-2
            - ap-southeast-1
            - ap-southeast-2
            - ap-northeast-1
            - eu-central-1
            - eu-west-1
            - eu-west-2
            - sa-east-1
    AUDIT_AWS_CLOUDWATCHLOGS_OWNER_TAG:
        description: "Enter an AWS tag whose value is an email address of the owner of the cloudwatchlogs object. (Optional)"
        required: false
        type: string
        default: "NOT_A_TAG"
    FILTERED_OBJECTS:
        description: "JSON object of string or regex of aws objects to include or exclude and tag in audit"
        required: false
        type: string
        default:
    AUDIT_AWS_CLOUDWATCHLOGS_S3_NOTIFICATION_BUCKET_NAME:
        required: false
        type: string
        default:
        description: "Enter S3 bucket name to upload reports. (Optional)"
        validations:
          - s3-bucket-name-validation
