variables:
    AUDIT_AWS_CLOUDWATCHLOGS_ALERT_LIST:
        required: false
        type: array
        default:
            - cloudwatchlogs-inventory # not_violation 
        description: "Which rules would you like to run? Possible values are cloudwatchlogs-inventory"
